### ISSUE TITLE
Dockerfile has dependency on image in private repository 

### ISSUE THREAD

**Issue by skalar-bcawkwell** [Skalar/soflow#35]
I was going to create a pull request which set the runtime for lambda to 8.10 (from 6.10), however I gave up trying to get watchexec to run myself, since you clearly already manged in trym/watchexec-alpine and there is only so much I enjoy getting glibc working.

Please make trym/watchexec-alpine available, or change how watchexec is added (or use some other tool).

**Comment by trym** [comment]
Was a bit over eager when cleaning up :D

Put back the image for backwards compat, but also pushed it to public docker/github as skalar/watchexec-alpine.
